version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 0

    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'storybook'
      - dependency-name: '@storybook/*'
      - dependency-name: 'react-router-dom'
      - dependency-name: '@typescript-eslint/*'
      - dependency-name: 'typescript'
      - dependency-name: 'vite'
      - dependency-name: '@vitejs/*'
      - dependency-name: 'eslint'
      - dependency-name: 'vitest'
